### PR TITLE
added extensions and paths to exclude

### PR DESCRIPTION
**Pull request by Zlays**
(fonts, dbs, ides, builds, icons and common tests)

### CODE REVIEW

**Comment by dub-flow** [comment]
Looks good! Thanks so much for your contribution!

**Comment by Zlays** [comment]
I put in but consider removing "test" from testPaths as it may be too generic

**Comment by dub-flow** [comment]
Agreed, I was actually wondering the same. Going forward, I intend to treat tests as follows:

- If a value for the flag `-tests` is provided, then only this path is used (and your added function is ignored)
- If `-tests` is not provided, then your function is used
 
Moreover, I think it makes sense to provide an extra flag, e.g. an `-include` flag, to explicitly specify folder names that should be included in case the tool automatically excludes something interesting. For example: Say the app is called "tester" or something, then `-include tester` would include all paths with "tester" in it despite the word "test" in it

**Comment by dub-flow** [comment]
I should have now solved the concern regarding "test" being too generic. Previously, e.g. a folder called "testimonals" would have been deleted. With the new check in place (https://github.com/fw10/veracode-javascript-packager/blob/main/utils.go#L86), only a folder called `e2e`, `test`, `__tests__` should be removed now.

**Pull request merged**
